<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
$productsAll = [
  [
    'id' => 1,
    'category' => 'PC Portable',
    'name' => 'HP 6F817EA',
    'price' => 11499,
    'rating' => 4,
    'color' => 'Black',
    'size' => 'Medium',
    'operatingSystem' => 'Windows',
    'brand' => 'Dell',
    'imgId' => 'xzelkgv4gyv9grdqobq7',
  ],
  [
    'id' => 2,
    'category' => 'PC Gamer',
    'name' => 'SG PCG ASTRO',
    'price' => 3749,
    'rating' => 5,
    'color' => 'Red',
    'size' => 'Large',
    'operatingSystem' => 'Windows',
    'brand' => 'Alienware',
    'imgId' => 'rtxdtnliaf6yoieb7siw',
  ],
  [
    'id' => 3,
    'category' => 'Telephone',
    'name' => 'SmartPhone A40',
    'price' => 3100,
    'rating' => 4,
    'color' => 'Blue',
    'size' => 'Medium',
    'operatingSystem' => 'Android',
    'brand' => 'Samsung',
    'imgId' => 'images/pbwuoh38kbcohsm8eaqc',
  ],
  [
    'id' => 4,
    'category' => 'PC Portable',
    'name' => 'Laptop Y',
    'price' => 12999,
    'rating' => 4,
    'color' => 'Silver',
    'size' => 'Large',
    'operatingSystem' => 'Windows',
    'brand' => 'HP',
    'imgId' => 'sdmmb5b4on6tnw1qitp8',
  ],
  [
    'id' => 5,
    'category' => 'PC Gamer',
    'name' => 'Gamer Elite',
    'price' => 1800.00,
    'rating' => 5,
    'color' => 'Black',
    'size' => 'Medium',
    'operatingSystem' => 'Windows',
    'brand' => 'MSI',
    'imgId' => 'images/gamer-elite',
  ],
  [
    'id' => 6,
    'category' => 'Telephone',
    'name' => ' Iphone 16',
    'price' => 8267,
    'rating' => 4.3,
    'color' => 'Green',
    'size' => 'Small',
    'operatingSystem' => 'iOS',
    'brand' => 'Apple',
    'imgId' => 'images/sc1gffoxjgxjj4dlkooo',
  ],
  [
    'id' => 7,
    'category' => 'PC Portable',
    'name' => 'Laptop Z',
    'price' => 850.00,
    'rating' => 3.8,
    'color' => 'Gray',
    'size' => 'Medium',
    'operatingSystem' => 'Windows',
    'brand' => 'Lenovo',
    'imgId' => 'images/laptop-z',
  ],
  [
    'id' => 8,
    'category' => 'PC Gamer',
    'name' => 'Gamer Max',
    'price' => 2500.00,
    'rating' => 5,
    'color' => 'Blue',
    'size' => 'Large',
    'operatingSystem' => 'Windows',
    'brand' => 'Razer',
    'imgId' => 'images/gamer-max',
  ],
  [
    'id' => 9,
    'category' => 'Telephone',
    'name' => 'Galaxy S23 Ultra',
    'price' => 750.99,
    'rating' => 4.2,
    'color' => 'Red',
    'size' => 'Medium',
    'operatingSystem' => 'Android',
    'brand' => 'OnePlus',
    'imgId' => 'images/q8hoe0720gitsmh0xzsw',
  ],
  [
    'id' => 10,
    'category' => 'PC Portable',
    'name' => 'Laptop A',
    'price' => 1300.00,
    'rating' => 4.1,
    'color' => 'White',
    'size' => 'Large',
    'operatingSystem' => 'Windows',
    'brand' => 'Acer',
    'imgId' => 'images/laptop-a',
  ],
  [
    'id' => 11,
    'category' => 'PC Gamer',
    'name' => 'Gamer Pro X',
    'price' => 2100.00,
    'rating' => 4.7,
    'color' => 'Red',
    'size' => 'Medium',
    'operatingSystem' => 'Windows',
    'brand' => 'Corsair',
    'imgId' => 'images/gamer-pro-x',
  ],
  [
    'id' => 12,
    'category' => 'Telephone',
    'name' => 'OPPO A38',
    'price' => 1789,
    'rating' => 4.8,
    'color' => 'Black',
    'size' => 'Large',
    'operatingSystem' => 'Android',
    'brand' => 'Google',
    'imgId' => 'images/ltyeelz0v1wc9hq746r1',
  ],
  [
    'id' => 13,
    'category' => 'PC Portable',
    'name' => 'Laptop B',
    'price' => 1100.00,
    'rating' => 4,
    'color' => 'Black',
    'size' => 'Medium',
    'operatingSystem' => 'Linux',
    'brand' => 'HP',
    'imgId' => 'images/laptop-b',
  ],
  [
    'id' => 14,
    'category' => 'PC Gamer',
    'name' => 'Gamer Titan',
    'price' => 2200.00,
    'rating' => 5,
    'color' => 'Silver',
    'size' => 'Large',
    'operatingSystem' => 'Windows',
    'brand' => 'Gigabyte',
    'imgId' => 'images/gamer-titan',
  ],
  [
    'id' => 15,
    'category' => 'Telephone',
    'name' => 'Galaxy S21 ',
    'price' => 3600,
    'rating' => 4.3,
    'color' => 'Gold',
    'size' => 'Small',
    'operatingSystem' => 'Android',
    'brand' => 'Apple',
    'imgId' => 'images/j38pifvsnkfomsxhy8jd',
  ],
  [
    'id' => 16,
    'category' => 'PC Portable',
    'name' => 'HP HP LAPTOP 15-DW3027NK (455X7EA)',
    'price' => 45000,
    'rating' => 3.9,
    'color' => 'Silver',
    'size' => 'Medium',
    'operatingSystem' => 'Windows',
    'brand' => 'Dell',
    'imgId' => 'lwn4615p9rslk3vvqzcq',
  ],
  [
    'id' => 17,
    'category' => 'PC Gamer',
    'name' => 'Gamer Prime',
    'price' => 1900.00,
    'rating' => 5,
    'color' => 'Black',
    'size' => 'Large',
    'operatingSystem' => 'Windows',
    'brand' => 'MSI',
    'imgId' => 'images/gamer-prime',
  ],
  [
    'id' => 18,
    'category' => 'Telephone',
    'name' => 'APPLE MYNG3',
    'price' => 13899,
    'rating' => 4.6,
    'color' => 'Pink',
    'size' => 'Medium',
    'operatingSystem' => 'iOS',
    'brand' => 'Xiaomi',
    'imgId' => 'images/wqoyfhrptqismgo6jbnx',
  ],
  [
    'id' => 19,
    'category' => 'PC Portable',
    'name' => 'Laptop D',
    'price' => 1350.00,
    'rating' => 4.2,
    'color' => 'Gray',
    'size' => 'Large',
    'operatingSystem' => 'Windows',
    'brand' => 'Asus',
    'imgId' => 'images/laptop-d',
  ],
  [
    'id' => 20,
    'category' => 'PC Gamer',
    'name' => 'Gamer Pro Z',
    'price' => 1700.00,
    'rating' => 5,
    'color' => 'Blue',
    'size' => 'Medium',
    'operatingSystem' => 'Windows',
    'brand' => 'Razer',
    'imgId' => 'images/gamer-pro-z',
  ],
  [
    'id' => 21,
    'category' => 'Jeu Vidéo',
    'name' => 'The Witcher 3: Wild Hunt',
    'price' => 59.99,
    'rating' => 5,
    'color' => 'N/A',
    'size' => 'N/A',
    'operatingSystem' => 'Windows',
    'brand' => 'CD Projekt',
    'imgId' => 'images/witcher-3',
  ],
  [
    'id' => 22,
    'category' => 'Jeu Vidéo',
    'name' => 'Red Dead Redemption 2',
    'price' => 49.99,
    'rating' => 5,
    'color' => 'N/A',
    'size' => 'N/A',
    'operatingSystem' => 'Windows',
    'brand' => 'Rockstar Games',
    'imgId' => 'images/red-dead-2',
  ],
  [
    'id' => 23,
    'category' => 'Jeu Vidéo',
    'name' => 'Cyberpunk 2077',
    'price' => 59.99,
    'rating' => 4.4,
    'color' => 'N/A',
    'size' => 'N/A',
    'operatingSystem' => 'Windows',
    'brand' => 'CD Projekt',
    'imgId' => 'images/cyberpunk-2077',
  ],
  [
    'id' => 24,
    'category' => 'Jeu Vidéo',
    'name' => 'Fortnite',
    'price' => 0.00,
    'rating' => 4.7,
    'color' => 'N/A',
    'size' => 'N/A',
    'operatingSystem' => 'Windows',
    'brand' => 'Epic Games',
    'imgId' => 'images/fortnite',
  ],
  [
    'id' => 25,
    'category' => 'Accessoires',
    'name' => 'Wireless Mouse',
    'price' => 29.99,
    'rating' => 4.3,
    'color' => 'Black',
    'size' => 'Small',
    'operatingSystem' => 'N/A',
    'brand' => 'Logitech',
    'imgId' => 'images/wireless-mouse',
  ],
  [
    'id' => 26,
    'category' => 'Accessoires',
    'name' => 'Gaming Keyboard',
    'price' => 59.99,
    'rating' => 4.6,
    'color' => 'RGB',
    'size' => 'Medium',
    'operatingSystem' => 'N/A',
    'brand' => 'Corsair',
    'imgId' => 'images/gaming-keyboard',
  ],
  [
    'id' => 27,
    'category' => 'Accessoires',
    'name' => 'Wireless Headset',
    'price' => 99.99,
    'rating' => 4.8,
    'color' => 'Blue',
    'size' => 'Medium',
    'operatingSystem' => 'N/A',
    'brand' => 'SteelSeries',
    'imgId' => 'images/wireless-headset',
  ],
  [
    'id' => 28,
    'category' => 'Accessoires',
    'name' => 'Phone Stand',
    'price' => 19.99,
    'rating' => 4.5,
    'color' => 'Black',
    'size' => 'Small',
    'operatingSystem' => 'N/A',
    'brand' => 'Anker',
    'imgId' => 'images/phone-stand',
  ],
  [
    'id' => 29,
    'category' => 'Accessoires',
    'name' => 'Mouse Pad',
    'price' => 15.99,
    'rating' => 4.0,
    'color' => 'Gray',
    'size' => 'Medium',
    'operatingSystem' => 'N/A',
    'brand' => 'Razer',
    'imgId' => 'images/mouse-pad',
  ],
  [
    'id' => 30,
    'category' => 'Accessoires',
    'name' => 'Laptop Sleeve',
    'price' => 25.00,
    'rating' => 4.4,
    'color' => 'Black',
    'size' => 'Medium',
    'operatingSystem' => 'N/A',
    'brand' => 'Targus',
    'imgId' => 'images/laptop-sleeve',
  ],
];




        DB::table('products')->insert($productsAll);
    }
}
