<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    $categories = [
      ['name' => 'Accessoires', 'icon_name' => 'FaHeadphones', 'href' => '/accessoires'],
      ['name' => 'PC Portable', 'icon_name' => 'FaLaptop', 'href' => '/pc-portable'],
      ['name' => 'Téléphone', 'icon_name' => 'SlScreenSmartphone', 'href' => '/telephone'],
      ['name' => 'Jeu Vidéo', 'icon_name' => 'FaGamepad', 'href' => '/jeu-video'],
      ['name' => 'PC Gamer', 'icon_name' => 'FaDesktop', 'href' => '/pc-gamer'],
    ];

    foreach ($categories as $category) {
      DB::table('categories')->insert($category);
    }

    // Insertion des produits avec des références de catégories
    $productsAll = [
      [
        'id' => 1,
        'category_id' =>2,
        'name' => 'HP 6F817EA',
        'price' => 11499,
        'rating' => 4,
        'color' => 'Black',
        'size' => 'Medium',
        'operatingSystem' => 'Windows',
        'brand' => 'Dell',
        'imgId' => 'xzelkgv4gyv9grdqobq7',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 2,
        'category_id' =>5,
        'name' => 'SG PCG ASTRO',
        'price' => 3749,
        'rating' => 5,
        'color' => 'Red',
        'size' => 'Large',
        'operatingSystem' => 'Windows',
        'brand' => 'Alienware',
        'imgId' => 'rtxdtnliaf6yoieb7siw',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 3,
        'category_id' => 3,
        'name' => 'SmartPhone A40',
        'price' => 3100,
        'rating' => 4,
        'color' => 'Blue',
        'size' => 'Medium',
        'operatingSystem' => 'Android',
        'brand' => 'Samsung',
        'imgId' => 'images/pbwuoh38kbcohsm8eaqc',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 4,
        'category_id' =>2,
        'name' => 'Laptop Y',
        'price' => 12999,
        'rating' => 4,
        'color' => 'Silver',
        'size' => 'Large',
        'operatingSystem' => 'Windows',
        'brand' => 'HP',
        'imgId' => 'sdmmb5b4on6tnw1qitp8',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 5,
        'category_id' =>5,
        'name' => 'SG PCG AIRFLOW',
        'price' => 3799,
        'rating' => 4,
        'color' => 'Black',
        'size' => 'Large',
        'operatingSystem' => 'Windows',
        'brand' => 'Airflow',
        'imgId' => 'pcgamer1_gv3ztc',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 6,
        'category_id' => 3,
        'name' => 'Iphone 16',
        'price' => 8267,
        'rating' => 4.3,
        'color' => 'Green',
        'size' => 'Small',
        'operatingSystem' => 'iOS',
        'brand' => 'Apple',
        'imgId' => 'images/sc1gffoxjgxjj4dlkooo',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 7,
        'category_id' =>2,
        'name' => 'ASUS VIVOBOOK SNAPDRAGON XELITE',
        'price' => 16999,
        'rating' => 4.5,
        'color' => 'White',
        'size' => 'Medium',
        'operatingSystem' => 'Windows',
        'brand' => 'Asus',
        'imgId' => 'laptop1_eozxzi',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 8,
        'category_id' =>5,
        'name' => 'SG PCG Vega 7',
        'price' => 3699,
        'rating' => 5,
        'color' => 'Black',
        'size' => 'Large',
        'operatingSystem' => 'Windows',
        'brand' => '',
        'imgId' => 'pcgamer2_pefbc4',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 9,
        'category_id' => 2,
        'name' => 'Galaxy S23 Ultra',
        'price' => 750.99,
        'rating' => 4.2,
        'color' => 'Red',
        'size' => 'Medium',
        'operatingSystem' => 'Android',
        'brand' => 'OnePlus',
        'imgId' => 's23_npfts9',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 10,
        'category_id' =>2,
        'name' => 'Asus ROG Zephyrus',
        'price' => 19000,
        'rating' => 4.5,
        'color' => 'Black',
        'size' => 'Medium',
        'operatingSystem' => 'Windows',
        'brand' => 'Asus',
        'imgId' => 'lp1_fxkhfw',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 11,
        'category_id' =>5,
        'name' => 'SETUP Gamer',
        'price' => 7999,
        'rating' => 4.7,
        'color' => 'Black',
        'size' => 'Medium',
        'operatingSystem' => 'Windows',
        'brand' => 'Corsair',
        'imgId' => 'pcg3_wzhtvc',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 12,
        'category_id' => 2,
        'name' => 'OPPO A38',
        'price' => 1789,
        'rating' => 4.8,
        'color' => 'Black',
        'size' => 'Large',
        'operatingSystem' => 'Android',
        'brand' => 'Google',
        'imgId' => 'images/ltyeelz0v1wc9hq746r1',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 13,
        'category_id' =>2,
        'name' => 'Gigabyte G6',
        'price' => 6500,
        'rating' => 4.5,
        'color' => 'Black',
        'size' => 'Medium',
        'operatingSystem' => 'Windows',
        'brand' => 'HP',
        'imgId' => 'lp2_ogmfzj',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 14,
        'category_id' =>5,
        'name' => 'SETUP Gamer',
        'price' => 4999,
        'rating' => 5,
        'color' => 'Black',
        'size' => 'Large',
        'operatingSystem' => 'Windows',
        'brand' => 'Gigabyte',
        'imgId' => 'pcg4_wq4syz',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 15,
        'category_id' => 2,
        'name' => 'Galaxy S21',
        'price' => 3600,
        'rating' => 4.3,
        'color' => 'Gold',
        'size' => 'Small',
        'operatingSystem' => 'Android',
        'brand' => 'Apple',
        'imgId' => 'images/j38pifvsnkfomsxhy8jd',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 16,
        'category_id' =>2,
        'name' => 'HP HP LAPTOP 15-DW3027NK (455X7EA)',
        'price' => 4500,
        'rating' => 3.9,
        'color' => 'Silver',
        'size' => 'Medium',
        'operatingSystem' => 'Windows',
        'brand' => 'Dell',
        'imgId' => 'lwn4615p9rslk3vvqzcq',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 17,
        'category_id' =>5,
        'name' => 'Gamer Prime',
        'price' => 1900.0,
        'rating' => 5,
        'color' => 'Black',
        'size' => 'Large',
        'operatingSystem' => 'Windows',
        'brand' => 'MSI',
        'imgId' => 'pcg4_eyoxk8',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 18,
        'category_id' => 2,
        'name' => 'APPLE MYNG3',
        'price' => 13899,
        'rating' => 4.6,
        'color' => 'Pink',
        'size' => 'Medium',
        'operatingSystem' => 'iOS',
        'brand' => 'Xiaomi',
        'imgId' => 'images/wqoyfhrptqismgo6jbnx',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 19,
        'category_id' =>2,
        'name' => 'MSI Stealth 16',
        'price' => 22000,
        'rating' => 4.7,
        'color' => 'Black',
        'size' => 'Large',
        'operatingSystem' => 'Windows',
        'brand' => 'MSI',
        'imgId' => 'lp2_z3uafb',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 20,
        'category_id' =>5,
        'name' => 'Gamer Pro Z',
        'price' => 29999,
        'rating' => 5,
        'color' => 'White',
        'size' => 'Large',
        'operatingSystem' => 'Windows',
        'brand' => 'Razer',
        'imgId' => 'pcg4_rvt8vs',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 21,
        'category_id' =>4,
        'name' => 'The Witcher 3: Wild Hunt',
        'price' => 59.99,
        'rating' => 5,
        'color' => 'N/A',
        'size' => 'N/A',
        'operatingSystem' => 'Windows',
        'brand' => 'CD Projekt',
        'imgId' => 'w_fyb1he',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 22,
        'category_id' =>4,
        'name' => 'Red Dead Redemption 2',
        'price' => 49.99,
        'rating' => 5,
        'color' => 'N/A',
        'size' => 'N/A',
        'operatingSystem' => 'Windows',
        'brand' => 'Rockstar Games',
        'imgId' => 'red_gq57vd',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 23,
        'category_id' =>4,
        'name' => 'Cyberpunk 2077',
        'price' => 59.99,
        'rating' => 4.4,
        'color' => 'N/A',
        'size' => 'N/A',
        'operatingSystem' => 'Windows',
        'brand' => 'CD Projekt',
        'imgId' => 'cyber_dhiszx',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 24,
        'category_id' =>4,
        'name' => 'Fortnite',
        'price' => 0.0,
        'rating' => 4.7,
        'color' => 'N/A',
        'size' => 'N/A',
        'operatingSystem' => 'Windows',
        'brand' => 'Epic Games',
        'imgId' => 'f_miyzaa',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 25,
        'category_id' =>1,
        'name' => 'Glorious Model O',
        'price' => 799,
        'rating' => 5,
        'color' => 'Black',
        'size' => 'Small',
        'operatingSystem' => 'N/A',
        'brand' => 'Glorious',
        'imgId' => 'mouse1_nfmtpn',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 26,
        'category_id' =>1,
        'name' => 'Redragon Cyrus Pro',
        'price' => 599,
        'rating' => 4.5,
        'color' => 'Green',
        'size' => 'Medium',
        'operatingSystem' => 'N/A',
        'brand' => 'Red Dragon',
        'imgId' => 'kb1_quvlv7',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 27,
        'category_id' =>1,
        'name' => 'Razer Kraken v3 X',
        'price' => 989,
        'rating' => 4.8,
        'color' => 'Black',
        'size' => 'Medium',
        'operatingSystem' => 'N/A',
        'brand' => 'Razer',
        'imgId' => 'headp1_dayous',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 28,
        'category_id' =>1,
        'name' => 'Logitech G102 LightSync',
        'price' => 199,
        'rating' => 4.5,
        'color' => 'White',
        'size' => 'Small',
        'operatingSystem' => 'N/A',
        'brand' => 'Logitech',
        'imgId' => 'mouse2_skbpdx',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 29,
        'category_id' =>1,
        'name' => 'ROG II Mousepad',
        'price' => 149,
        'rating' => 4.0,
        'color' => 'Black',
        'size' => 'Large',
        'operatingSystem' => 'N/A',
        'brand' => 'ROG',
        'imgId' => 'mp1_lhekso',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 30,
        'category_id' =>1,
        'name' => 'HyperX Quadcast S RGB',
        'price' => 1649,
        'rating' => 4.8,
        'color' => 'White',
        'size' => 'Medium',
        'operatingSystem' => 'N/A',
        'brand' => 'HyperX',
        'imgId' => 'mic1_ijpigh',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 31,
        'category_id' =>1,
        'name' => 'ASUS TUF Gaming VG279Q3A 27',
        'price' => 1999,
        'rating' => 4.5,
        'color' => 'Black',
        'size' => 'Large',
        'operatingSystem' => 'N/A',
        'brand' => 'Asus',
        'imgId' => 'monitor1_jew4p4',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'id' => 32,
        'category_id' => 2,
        'name' => 'Iphone 15 Pro Max',
        'price' => 20000,
        'rating' => 5,
        'color' => 'Blue',
        'size' => 'Medium',
        'operatingSystem' => 'iOS',
        'brand' => 'Iphone',
        'imgId' => 'iphone15_tp7mic',
        'created_at' => now(),
        'updated_at' => now(),
      ],
      // Ajoutez d'autres produits ici
    ];

    DB::table('products')->insert($productsAll);
  }
}
